version: '3'

services:
  db:
    container_name: mongo
    build: ./mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example  
  server:
    container_name: stock_server
    build: ./server
    environment:
      MONGO_LINK: mongodb://root:example@mongo:27017
    links:
      - db
    ports:
      - 5000:5000  
  client:
    container_name: stock_client
    build: ./client
    environment:
      SERVER: http://stock_server:5000/
    links:
        - server
    ports:
      - 3000:3000